### ISSUE TITLE
Can't start corectld

### ISSUE THREAD

**Issue by jacobat** [AntonioMeireles/coreos-xhyve#80]
Not sure what's going on here. After upgrading to 0.7 I get this:

```
$ corectld start -u jacob
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address
[ERROR] exit status 1
$ ls /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist
ls: /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist: No such file or directory
```

**Comment by AntonioMeireles** [comment]
(On the beach and from my mobile)

Do you have Internet sharing enabled? If no do please. Should fix that
error, at sight

**Comment by jacobat** [comment]
I've enabled Internet Sharing in SystemPreferences, but the file still isn't there.

**Comment by AntonioMeireles** [comment]
What macOS version are you on?

**Comment by jacobat** [comment]
10.11.5 (15F34)

**Comment by jacobat** [comment]
I don't know if it matter, but this machine was just reinstalled.

**Comment by jacobat** [comment]
Copying a `com.apple.vmnet.plist` from a backup into the right place allows me to start `corectld`

**Comment by AntonioMeireles** [comment]
@jacobat above patch, to be in 0.7.7, should get this addressed fully. thanks for reporting!

**Comment by AntonioMeireles** [comment]
fixed in 0.7.9

**Comment by nicwolff** [comment]
```
$ corectld version
 Version:   0.7.15
 Go Version:    go1.6.3
 Built:     Wed Aug 03 16:49:26 BST 2016
 OS/Arch:   darwin/amd64

$ corectld start
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)
^[[ERROR] Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.
```

**Comment by AntonioMeireles** [comment]
Strange. What macOS version? Thanks!

**Comment by nyaaao** [comment]
@AntonioMeireles I experience the same problem. Installed via homebrew.
This is what I get:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A313a
```

```
$ corectld version
 Version:   0.7.15
 Go Version:    go1.7.1
 Built:     Sun Sep 11 14:46:30 IDT 2016
 OS/Arch:   darwin/amd64
```

```
$ corectld -d start
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)
[ERROR] Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.

panic: Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.


goroutine 1 [running]:
panic(0x49e6600, 0xc420262f00)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log.Die(0xc420132ee0, 0x69, 0x0, 0x0, 0x0)
    /private/tmp/corectl-20160911-16795-w9kfdi/corectl-0.7.15/src/github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log/log.go:46 +0xfe
main.main()
    /private/tmp/corectl-20160911-16795-w9kfdi/corectl-0.7.15/src/github.com/TheNewNormal/corectl/cmd/server/main.go:77 +0x83
```

What can I do to troubleshoot this further?

PS: this also prevents Corectl app from starting the server correctly.

**Comment by AntonioMeireles** [comment]
ok, i moved to macOS Sierra GM last friday and on my setups odly both the blobs built previously and new blobs work flawlessly. i'll debug over today this with @rimusz, as he is hitting (#80) similar issues, to sort it out ,as it is simpler.

@nyaaao if your issue turns to be a different one i'll get back to you so that we can dig this further together.

thanks  all for your patience!

**Comment by nyaaao** [comment]
thank you for looking into this @AntonioMeireles. I'm going to upgrade to Sierra GM today and see if it solves the issue.

**Comment by AntonioMeireles** [comment]
@nyaaao please be aware that atm the issues are _mostly_ in sierra it seems...

**Comment by rimusz** [comment]
I'm also encountering problem on Sierra first start `corectld start --user $(whoami) --debug` always hangs after asking for password window, `debug` option returns nothing.
hmm, canceling and repeating command does not work for me anymore.

**Comment by nyaaao** [comment]
@AntonioMeireles @rimusz upgrading to macOS Sierra GM fixed this for me

**Comment by rimusz** [comment]
@AntonioMeireles got these errors on `corectl halt -a` and VM was not halted :

```
corectl halt -a
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x64fa9018f58 pc=0x401bb3b]

runtime stack:
runtime.throw(0x51f8f40, 0x2a)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x580b920)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x580b920, 0x1, 0x3, 0x5c09e68)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff568)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x580b920, 0x1, 0x10000000003, 0x401b7df)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x580cd40, 0x0)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x580cd40, 0x5c09e68)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x58604b0, 0x3, 0x5c09e68)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x5803600)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc8201c65b8 sp=0xc8201c65b0
runtime.mallocgc(0x20, 0x4e75aa0, 0x0, 0xc8201fffe0)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc8201c6690 sp=0xc8201c65b8
runtime.newobject(0x4e75aa0, 0xc8201fffe0)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc8201c66b8 sp=0xc8201c6690
github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack.addDecoderNode(0x3ffffec0500cff2, 0x2)
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack/huffman.go:144 +0x26c fp=0xc8201c6738 sp=0xc8201c66b8
github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack.init.1()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack/huffman.go:127 +0x86 fp=0xc8201c6b80 sp=0xc8201c6738
github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/hpack/tables.go:352 +0x1f7a fp=0xc8201c6bf8 sp=0xc8201c6b80
github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/golang.org/x/net/http2/writesched.go:283 +0x7f fp=0xc8201c6c90 sp=0xc8201c6bf8
github.com/TheNewNormal/corectl/vendor/google.golang.org/grpc/transport.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/google.golang.org/grpc/transport/transport.go:559 +0x51 fp=0xc8201c6ce8 sp=0xc8201c6c90
github.com/TheNewNormal/corectl/vendor/google.golang.org/grpc.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/google.golang.org/grpc/trace.go:119 +0x7e fp=0xc8201c6d10 sp=0xc8201c6ce8
github.com/TheNewNormal/corectl/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:1866 +0x78 fp=0xc8201c7c88 sp=0xc8201c6d10
github.com/TheNewNormal/corectl/vendor/github.com/coreos/etcd/etcdserver.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/vendor/github.com/coreos/etcd/etcdserver/v3_server.go:606 +0x64 fp=0xc8201c7ec0 sp=0xc8201c7c88
github.com/TheNewNormal/corectl/components/server.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/components/server/vpn.go:83 +0x8d fp=0xc8201c7f00 sp=0xc8201c7ec0
github.com/TheNewNormal/corectl/components/common.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/components/common/common.go:198 +0x65 fp=0xc8201c7f18 sp=0xc8201c7f00
main.init()
    /Users/am/go/src/github.com/TheNewNormal/corectl/cmd/client/ssh.go:125 +0x4c fp=0xc8201c7f30 sp=0xc8201c7f18
runtime.main()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:177 +0x27f fp=0xc8201c7f80 sp=0xc8201c7f30
runtime.goexit()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201c7f88 sp=0xc8201c7f80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by AntonioMeireles** [comment]
closing, afaict this is no longer an issue. please reopen if i happen to be wrong :-)
